version: '3.8'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile-app
    ports:
      - 8080:8080
  app-db:
    image: postgres:13.3
    container_name: app-db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intershopdb
    volumes:
      - app-db-data:/val/lib/postgresql/data
  app-cache-db:
    image: redis:7.4-bookworm
    container_name: app-cache-db
    ports:
      - 6379:6379
    command: ["redis-server"]
  app-session-db:
    image: redis:7.4-bookworm
    container_name: app-session-db
    ports:
      - 6380:6380
    command: [ "redis-server", "--port 6380"]
  payment:
    container_name: payment
    build:
      context: .
      dockerfile: Dockerfile-payment
    ports:
      - 8081:8081
    command: java -jar /app/payment.jar
  payment-db:
    image: postgres:13.3
    container_name: payment-db
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paymentdb
    volumes:
      - payment-db-data:/val/lib/postgresql/data
  auth-server:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: auth-server
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - 9090:8082
    volumes:
      - ./realm-config:/opt/keycloak/data/import
    command: start-dev --import-realm --http-port=8082

volumes:
  app-db-data:
  payment-db-data: