version: '3.8'

services:
  app:
    image: openjdk:21-jdk-slim
    container_name: intershop
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./build/libs/intershop.jar:/app/intershop.jar
    command: java -jar /app/intershop.jar
  db:
    image: postgres:13.3
    container_name: db
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: intershopdb
    volumes:
      - db-data:/val/lib/postgresql/data

  cache-db:
    image: redis:7.4-bookworm
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server"]



volumes:
  db-data: