app:
  partition-count: 4

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/intershopdb
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5433/intershopdb
    user: postgres
    password: postgres
  sql:
    init:
      mode: never
  redis:
    cache:
      host: localhost
      port: 6379
      time-to-live-seconds: 60
    session:
      host: localhost
      port: 6380

