spring:
  r2dbc:
    url: r2dbc:postgresql://app-db:5432/intershopdb
  liquibase:
    url: jdbc:postgresql://app-db:5432/intershopdb
  sql:
    init:
      mode: always
  redis:
    cache:
      host: app-cache-db
    session:
      host: app-session-db
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://auth-server:8082/realms/master