server:
  port: 8081

app:
  start-balance: 10000

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5434/paymentdb
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    url: jdbc:postgresql://localhost:5434/paymentdb
    user: postgres
    password: postgres
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/master
