openapi: 3.0.3
info:
  title: Payment Service API
  version: 1.0.0
servers:
  - url: http://{host}:8081
    variables:
      host:
        default: localhost

tags:
  - name: Balance
    description: Endpoints related to checking user balance
  - name: Payments
    description: Endpoints related to making payments

paths:
  /balance:
    get:
      summary: Get user's current balance
      tags:
        - Balance
      parameters:
        - $ref: '#/components/parameters/UserId'
      responses:
        "200":
          description: Current balance retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BalanceResponse"
      x-content-type: application/json
      x-accepts:
        - application/json
  /pay:
    post:
      summary: Process a payment by deducting amount from user's balance
      tags:
        - Payments
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PaymentRequest"
      responses:
        "200":
          description: Payment successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "400":
          description: Insufficient funds or invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentResponse"
      x-content-type: application/json
      x-accepts:
        - application/json
components:
  parameters:
    UserId:
      name: userId
      in: query
      required: true
      description: User's ID
      schema:
        type: integer
        format: int64
  schemas:
    BalanceResponse:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        balance:
          type: number
          format: double
      example:
        user_id: 1
        balance: 5000
    PaymentRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        amount:
          type: number
          format: double
      example:
        user_id: 1
        amount: 2000
    PaymentResponse:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        new_balance:
          type: number
          format: double
        success:
          type: boolean
        message:
          type: string
      example:
        user_id: 1
        new_balance: 3000
        success: true
        message: "Payment successful"
